# Generated by Django 4.1.5 on 2023-01-30 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('product_type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('specs', models.TextField()),
                ('buying_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_state', models.CharField(choices=[('O', 'Okay'), ('A', 'Abnormal'), ('D', 'Dead')], default='O', max_length=1)),
                ('returned_date', models.DateTimeField(auto_now=True, null=True)),
                ('returned_state', models.CharField(choices=[('O', 'Okay'), ('A', 'Abnormal'), ('D', 'Dead')], default='O', max_length=1)),
                ('assigned_to_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.product')),
            ],
        ),
    ]
