# Generated by Django 4.1.5 on 2023-01-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assignedproduct_returned_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedproduct',
            name='tag',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
