# Generated by Django 4.1.5 on 2023-01-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assignedproduct_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedproduct',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
