# Generated by Django 4.1.5 on 2023-01-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assignedproduct_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedproduct',
            name='returned_state',
            field=models.CharField(blank=True, choices=[('O', 'Okay'), ('A', 'Abnormal'), ('D', 'Dead')], max_length=1, null=True),
        ),
    ]
